from app.core.roles import RoleName

PLAYER_VIEW_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
    RoleName.ANALYST,
    RoleName.SPORTS_SCIENTIST,
    RoleName.MEDICAL_STAFF,
    RoleName.SCOUT,
)
PLAYER_CREATE_ROLES = (RoleName.ADMIN, RoleName.DIRECTOR, RoleName.HEAD_COACH)
PLAYER_UPDATE_ROLES = (*PLAYER_CREATE_ROLES, RoleName.ASSISTANT_COACH)
PLAYER_DELETE_ROLES = (RoleName.ADMIN, RoleName.DIRECTOR)
STAFF_VIEW_ROLES = PLAYER_VIEW_ROLES
STAFF_MANAGE_ROLES = PLAYER_CREATE_ROLES
TEAM_VIEW_ROLES = PLAYER_VIEW_ROLES
TEAM_MANAGE_ROLES = PLAYER_CREATE_ROLES
TEAM_DELETE_ROLES = (RoleName.ADMIN, RoleName.DIRECTOR)
MEMBERSHIP_MANAGE_ROLES = (*PLAYER_CREATE_ROLES, RoleName.ASSISTANT_COACH)

TRAINING_READ_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
    RoleName.ANALYST,
    RoleName.SPORTS_SCIENTIST,
)
TRAINING_SESSION_MANAGE_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
)
TRAINING_PARTICIPATION_MANAGE_ROLES = (
    *TRAINING_SESSION_MANAGE_ROLES,
    RoleName.SPORTS_SCIENTIST,
)
TRAINING_PARTICIPATION_CREATE_ROLES = TRAINING_SESSION_MANAGE_ROLES
TRAINING_PARTICIPATION_DELETE_ROLES = TRAINING_SESSION_MANAGE_ROLES
SPORTS_SCIENTIST_TRAINING_FIELDS = frozenset(
    {"planned_load", "actual_load", "duration_minutes"}
)
AVAILABILITY_READ_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
    RoleName.MEDICAL_STAFF,
)
AVAILABILITY_MANAGE_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.MEDICAL_STAFF,
)
DEVELOPMENT_READ_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
    RoleName.ANALYST,
    RoleName.SCOUT,
)
DEVELOPMENT_MANAGE_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
)

MATCH_READ_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
    RoleName.ANALYST,
    RoleName.SPORTS_SCIENTIST,
    RoleName.MEDICAL_STAFF,
    RoleName.SCOUT,
)
MATCH_MANAGE_ROLES = (
    RoleName.ADMIN,
    RoleName.DIRECTOR,
    RoleName.HEAD_COACH,
    RoleName.ASSISTANT_COACH,
)
MATCH_EVENT_WRITE_ROLES = (*MATCH_MANAGE_ROLES, RoleName.ANALYST)
MATCH_EVENT_DELETE_ROLES = MATCH_MANAGE_ROLES
MATCH_CATALOG_MANAGE_ROLES = (RoleName.ADMIN, RoleName.DIRECTOR)

ASSISTANT_PLAYER_FIELDS = frozenset(
    {
        "preferred_position",
        "secondary_position",
        "squad_number",
        "dominant_foot",
        "height_cm",
        "weight_kg",
    }
)
