from enum import StrEnum


class RoleName(StrEnum):
    HEAD_COACH = "HEAD_COACH"
    ASSISTANT_COACH = "ASSISTANT_COACH"
    ANALYST = "ANALYST"
    SPORTS_SCIENTIST = "SPORTS_SCIENTIST"
    MEDICAL_STAFF = "MEDICAL_STAFF"
    SCOUT = "SCOUT"
    PLAYER = "PLAYER"
    DIRECTOR = "DIRECTOR"
    ADMIN = "ADMIN"
